### ISSUE TITLE
Docker exit code 134

### ISSUE THREAD

**Issue by TeamMadnessGames** [game-ci/unity-actions#108]
I am getting this error: 

Does anyone know why? Any possible solutions?

![Captura_de_pantalla_2021-06-19_225649](https://user-images.githubusercontent.com/86007094/122657318-ceb68380-d162-11eb-9a4e-f47b71e64028.png)

I am using unity 2019.4.23f1

Here is the building script: 

![Captura de pantalla 2021-06-20 010052](https://user-images.githubusercontent.com/86007094/122657338-f9a0d780-d162-11eb-89a1-1c0f1c9c0358.png)

**Comment by webbertakken** [comment]
Thanks for your bug report @TeamMadnessGames!

Core dumped at line `23448` tells me that the build was already running for a while. The rest of both screenshots is not very helpful. What you could do is check what happens before the core is dumped. i.e. did it tell you anything about why the core was dumped?

If it doesn't tell anything at all then I would recommend checking if you ran of out memory or disk space. For the latter you can clear some files to create up to ~60GB of disk space on default github (azure) runners.

As for your config, we do not recommend manually specifying options if you're using defaults. Project path is redundant and unity version is detected automatically based on your project. Library cache key also doesn't need project path as you only have one of them. These changes would simplify your workflow by 20%.

**Comment by TeamMadnessGames** [comment]
@webbertakken Hello! thanks for the reply, here I think it may help, this is just before the core dump 

I hope this helps track the issue, I have been al the day trying to look for a solution but I am kind of desperate now ^^"

![Captura de pantalla 2021-06-20 020837](https://user-images.githubusercontent.com/86007094/122658367-9caa1f00-d16c-11eb-8774-90cf65c9bac4.png)

**Comment by webbertakken** [comment]
We have seen errors with `funlockfile` before. Usually it has to do with either using or not using `-nographics` flag, which sometimes doesn't work due to a Unity bug that seemingly only occurs in linux in some 2019.3 and 2019.4 versions.

Could you try `v2.0-alpha-10` and see if that helps?

**Comment by TeamMadnessGames** [comment]
@webbertakken When you say trying `v2.0-alpha-10` what do you mean? sorry if it sounds like a stupid question I am pretty new on these things ^^"

**Comment by webbertakken** [comment]
My bad, I could have been less ambiguous about that.

What I meant was the latest alpha version of unity-builder. See also [releases](https://github.com/game-ci/unity-builder/releases).

**Comment by TeamMadnessGames** [comment]
@webbertakken Okay! I just changed the version of the unity-builder, I will reply again when its done with feedback ^^

**Comment by TeamMadnessGames** [comment]
@webbertakken Build finished correctly and working fine! Thanks for your help & time! One last question about what you mentioned before, should I then delete the manually specified options like unity version & lib cache key?

**Comment by davidmfinol** [comment]
@TeamMadnessGames Yes, would recommend removing unity version and project path from your config, as it is better to use the defaults.

Closing this issue since it seems it is working fine for you now.
