### ISSUE TITLE
Failing tests should fail the job

### ISSUE THREAD

**Issue by KurtGokhan** [game-ci/unity-actions#109]
**Bug description**

I am using `game-ci/unity-test-runner@v2` in my Github Action. My expectation was that when the tests fails for some reason, it marks the Action as failed. But in my case there was compile errors in script and tests were not run. 

**How to reproduce**

It happens when the tests can't run for some reason. In my case there was compile errors in the script, so tests were not run.

**Expected behavior**

Github Action should fail and be marked with red when there is a failure in tests or tests cannot be run for some reason.

**Additional details**

This behavior can be seen in [my repo](https://github.com/ReactUnity/core/runs/2976916402?check_suite_focus=true#step:7:1000)

As you see, the tests [have failed](https://github.com/ReactUnity/core/runs/2976916402?check_suite_focus=true#step:7:1711) but the overall job was successful.

Edit: Github deletes old logs. Ping me if you need a recent log.

**Comment by davidmfinol** [comment]
This is fixed now.
