### ISSUE TITLE
The process '/usr/bin/docker' failed with exit code 139 (probably related to PackSpriteAtlases)

### ISSUE THREAD

**Issue by SerG-Y** [game-ci/unity-actions#122]
**Bug description**
This issue happens when I am using unity sprite atlas for spine animation (attached screenshot with the error). I don't really know what happens, I tried to use different unity version but it doesn't help only removing usage of sprite atlas helps. Locally builds runs successfully. Any help is appreciated! Maybe it's possible to run it locally with `game-ci/unity-builder@v2` to debug it somehow? 
 

**How to reproduce**

- pack images which using in spine animation into a sprite atlas(`Create -> 2D -> Sprite Atlas`)
- than import it using `Window -> Spine -> SpriteAtlas import`
- Try to run build using `game-ci/unity-builder@v2`

**Expected behavior**
Successful build

**Additional details**

![image](https://user-images.githubusercontent.com/12532719/135712849-2eac91ce-b396-4d79-a979-31d32be020a3.png)
![image](https://user-images.githubusercontent.com/12532719/135713185-8a4643ef-3a12-4114-a0fd-43f476a64977.png)

**Comment by davidmfinol** [comment]
Hi @SerG-Y , can you create a public repo that reproduces the issue, and share a link to the logs of a failing build?
I could take a look if you do.

**Comment by SerG-Y** [comment]
@davidmfinol sorry for the long response, missed it. I think we can close this issue as I guess it's not `unity-builder`  issue. I think it's `unity 2021.1.*` issue. I changed the setting `Editor->SpritePacker->Mode` to `Sprite Atlas v2` and this fixed the issue. Thanks for reply!

**Comment by davidmfinol** [comment]
Cool, closed. Glad you got it working.
