### ISSUE TITLE
caching can by embedded to main action due to needed in the 99% cases except some unique

### ISSUE THREAD

**Issue by Dukobpa3** [game-ci/unity-actions#126]
https://github.com/actions/toolkit/tree/main/packages/cache

**Comment by webbertakken** [comment]
Excellent idea. 

In case we want to support this we would need to support each action, but particularly `unity-test-runner` and `unity-builder`. I'm curious if it's feasible when using multiple actions in a single workflow; when cache gets changed or invalidated in either of these actions.

We would also have to come up with some strategy for the cache key. Perhaps it could be as simple as making a composite key based on some of the parameters (i.e. `targetPlatform`) possibly in conjunction with a hash of the packages manifest file.

What are your thoughts on this?

**Comment by Dukobpa3** [comment]
Here is few answers about "Run ID".
I think we can operate wit it as key.
Also provide option to describe key directly. Maybe I'll want to run two actions in the flow with cleanup between them.

https://github.community/t/how-to-get-the-run-id/16587
