### ISSUE TITLE
How do I enable 'Server Build' option?

### ISSUE THREAD

**Issue by fruitdrawing** [game-ci/unity-actions#132]
I seeing only platform options for standalone for each platform.

forexmple : 

matrix:
        targetPlatform:
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.

**But If I would like to enable server build option, how do I do that? Is there any options for yaml file?**

Thanks in advance.

**Comment by webbertakken** [comment]
Could you perhaps try `customParameters: -EnableHeadlessMode`

Custom parameters option is documented [here](https://game.ci/docs/github/builder#customparameters) and allows passing through any [editor cli arguments](https://docs.unity3d.com/2019.3/Documentation/Manual/CommandLineArguments.html) to the editor too

**Comment by davidmfinol** [comment]
We've updated the docs to explicitly mention `customParameters: -EnableHeadlessMode` for server builds, as I did see confirmation elsewhere on discord.
Closing this issue, but feel free to re-open if there is still any doubt.
