### ISSUE TITLE
support for macos runners disabled?

### ISSUE THREAD

**Issue by oshaughnessy** [game-ci/unity-actions#138]
**Bug description**

Hello. I'm trying to build a StandalonOSXClient on the GitHub macos-latest runner and I get this error:

> Error: Currently darwin-platform is not supported

The [docs](https://game.ci/docs/github/getting-started#advanced-il2cpp-example) suggest it should work.

**How to reproduce**

Define a GitHub Actions workflow with `runs-on: macos-latest` and attempt to use `game-ci/unity-builder@v2` to build the project.

**Expected behavior**

I was expecting an attempt to build the Unity project.

**Additional details**

I'm expecting this is known behavior. The IL2CPP example in the GitHub actions page shows how to use the macos runner, so that makes me think there are plans to support it again someday. I'm curious where that might be on your roadmap. What are the current issues with it? Perhaps I can contribute.

Thank you, and best regards.

**Comment by AndrewKahr** [comment]
Ooops I think the docs got a little ahead of the releases. If you use @main instead of @v2 it should be able to build mac il2cpp.
