### ISSUE TITLE
Manifest unknown (unityci/editor:2021.2.17f1-base-0)

### ISSUE THREAD

**Issue by brookman** [game-ci/unity-actions#141]
**The workflow tries to use a non-existing docker image tag**

The github action / workflow tries to pull an image which does not exist. Error message:
`manifest for unityci/editor:2021.2.17f1-base-0 not found: manifest unknown: manifest unknown`
The correct tag would be `2021.2.17f1-base-1.0.0`

**How to reproduce**

Create a new Unity project with 2021.2.17f1. Follow the steps [here](https://game.ci/docs/github/getting-started).

**Expected behavior**

Docker should use the image `2021.2.17f1-base-1.0.0` not `2021.2.17f1-base-0`

**Additional details**

**Comment by Kuhpik** [comment]
This is a bug because existing workflows are broken right now. We have to pass "customImage" param to make it work again.

**Comment by webbertakken** [comment]
It doesn't break existing workflows. Only if you upgrade your project to a version that's not supported yet.

Either way we're planning to release version 2 in the coming couple of weeks.

**Comment by brookman** [comment]
I have found that using versions 2021.2.16f1 and 2021.2.18f1 work. Only 2021.2.17f1 returns an error.

**Comment by webbertakken** [comment]
> I have found that using versions 2021.2.16f1 and 2021.2.18f1 work. Only 2021.2.17f1 returns an error.

Which error are you getting on `2021.2.17f1`? I suppose you're no longer getting the manifest error right?

By the way in `v2.0.0` of the unity actions we have switched to `v1` of the images (see [versions](https://game.ci/docs/docker/versions))
