### ISSUE TITLE
Error: Branch is dirty. Refusing to base semantic version on uncommitted changes

### ISSUE THREAD

**Issue by fgsoftware1** [game-ci/unity-actions#145]
[repository](https://github.com/fgsoftware1/survival/blob/master/.github/workflows/CI.yml)

**Comment by webbertakken** [comment]
Branch dirty means that during the CI workflow files changed after checkout, which shouldn't happen.

Be sure to use a .gitignore file in your project that ignores `Library` and `artifacts`

**Comment by fgsoftware1** [comment]
> Branch dirty means that during the CI workflow files changed after checkout, which shouldn't happen.
> 
> Be sure to use a .gitignore file in your project that ignores `Library` and `artifacts`

error persist

**Comment by webbertakken** [comment]
Seems in CI you have asset files that aren't checked in to VCS.

Please have a look at the log to see which files.

**Comment by fgsoftware1** [comment]
> Seems in CI you have asset files that aren't checked in to VCS.
> 
> Please have a look at the log to see which files.

Warning: Changes were made to the following files and folders:

Warning:  M Assets/AppCenter/Editor/AppCenterIcon.png
