### ISSUE TITLE
¿How to build .aab file with ApiLevel 31?

### ISSUE THREAD

**Issue by Juanda9992** [game-ci/unity-actions#151]
**¿How can i build a .aab file with the Api Level 31?**

**I am using the Builder Action with the AndroidAppBundle parameter set to true, the .aab file is created successfully but when i want to upload this file to the play store, it says that the Api level required is 31, but the .aab file has api level of 30**

Here is my action

`       -uses: game-ci/unity-builder@v2

        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          androidAppBundle: true
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          androidTargetSdkVersion: AndroidApiLevelAuto
      - uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.targetPlatform }}
          path: build/${{ matrix.targetPlatform }}`

**Expected behavior**

I have the sdk installed with the Api level of 31, so when i set androidTargetSdkVersion: AndroidApiLevelAuto i expected that the .aab file must have the Api level of 31.

**Comment by davidmfinol** [comment]
This is fixed by https://github.com/game-ci/unity-builder/pull/425
