### ISSUE TITLE
Choose Log Level

### ISSUE THREAD

**Issue by trungdlp-wolffun** [game-ci/unity-actions#153]
**Context**

I use GameCI build pipeline on my games, but I see over warning, errors message. I can't detect my problem easy. I must scroll and find every line to find cause error. I tried, I just want know exactly right way.

**Suggested solution**

I think, add new feature set logging level by ENV or parameters:
Example Log Level:
- TRACE
- DEBUG
- INFO
- WARN
- ERROR
- FATAL

**Considered alternatives**

**Additional details**

**Comment by webbertakken** [comment]
Three features will be covered by https://github.com/game-ci/unity-builder/pull/413 to accommodate for this.

- Verbosity levels `--quiet`, `-v`, `-vv`, `-vvv`
- Log files where the lines include their log levels, like the ones you described.
- Improved granularity of what it being logged, and on which level.

The next step is to take that logic out and move it to a new `cli` repository. The CLI will be the basis for all unity-actions. 

Progress can be followed on our [roadmap](https://github.com/orgs/game-ci/projects/4/views/1).

**Comment by trungdlp-wolffun** [comment]
@webbertakken Thank for your answer !
