### ISSUE TITLE
Use node16 instead of node12 for provided GitHub Actions

### ISSUE THREAD

**Issue by ChristianTellefsen** [game-ci/unity-actions#157]
**Context**

[Node 12 actions are now deprecated](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) by GitHub.

**Suggested solution**

Use node16 instead of node12 for provided GitHub Actions. See link above.

**Additional details**

Warning that appears in GitHub Actions:

![Screenshot 2022-10-12 093945](https://user-images.githubusercontent.com/1049621/195280533-70b56fd6-bf4a-4285-85db-618b24fcd6e9.png)

**Comment by davidmfinol** [comment]
This upgrade has been completed, so closing this issue.
