### ISSUE TITLE
How to add modules to Unity Editor during build?

### ISSUE THREAD

**Issue by Chendisen** [game-ci/unity-actions#167]
Hi, I have looked around in the FAQ and other open and closed issues but haven't found a good answer to my problem. 

I'm having a problem that the Unity Editor I use has an added extra module that is necessary for my project. So I suspect that the Unity that is used when building the project as part of the workflow don't have the module installed. 
Is there a way to make sure that the Unity Editor that is used in the workflow has the desired module installed? The desired module is: Linux Build Support (IL2CPP). 

This might be a trivial matter, but I haven't really found any documentation about it. There were some issues and answers about IL2CPP, but it didn't seem to match my problem. Would help a lot if someone could help me with this.

**Comment by davidmfinol** [comment]
If you're using `game-ci/unity-builder@v2` and building on Linux, it will include Linux Build Support (IL2CPP) by default.
You could confirm by checking in your logs to see the image which is being used. It should look like `unityci/editor:ubuntu-<version>-linux-il2cpp-1`.

However, if you're using a different method or platform for building, you may indeed need to roll your own image.
