### ISSUE TITLE
Docker exited with exit code 103: MemoryLeaks

### ISSUE THREAD

**Issue by Beatzoid** [game-ci/unity-actions#171]
**Bug description**

Whenever I try to build a Unity project using [this](https://github.com/Beatzoid/tactics-rpg/blob/28d23a320cf4ea11f460130da16f2ee85d807236/.github/workflows/main.yml) CI config, it fails with the error code 103, and the only error I could find was this:

<details>
<summary>Error</summary>
<code>{"type":"MemoryLeaks","version":2,"phase":"Immediate","time":1682291967194,"processId":99,"allocatedMemory":12407642,"memoryLabels":[{"Default":11511},{"Permanent":16296},{"Thread":1083564},{"Manager":17627},{"VertexData":12},{"Geometry":280},{"Texture":168},{"Shader":69428},{"Material":24},{"GfxDevice":36320},{"Animation":352},{"Audio":3976},{"FontEngine":336},{"Physics":561},{"Serialization":684},{"Input":26808},{"JobScheduler":232},{"Mono":40},{"ScriptingNativeRuntime":43704},{"BaseObject":1620332},{"Resource":856},{"Renderer":2184},{"Transform":48},{"File":1206125},{"WebCam":40},{"Culling":40},{"Terrain":1025},{"Wind":24},{"String":30128},{"DynamicArray":145800},{"HashMap":105117},{"Utility":288350},{"Curl":1112},{"PoolAlloc":592640},{"AI":40},{"TypeTree":4533},{"ScriptManager":528},{"RuntimeInitializeOnLoadManager":72},{"SpriteAtlas":112},{"GI":3552},{"Director":7928},{"CloudService":4208},{"WebRequest":720},{"VR":45705},{"SceneManager":640},{"Video":72},{"LazyScriptCache":32},{"NativeArray":12},{"Camera":25},{"Secure":6161},{"Image":278528},{"SerializationCache":1576},{"APIUpdating":11856},{"Subsystems":384},{"VirtualTexturing":57560},{"StaticSafetyDebugInfo":327680},{"EditorGui":56},{"EditorUtility":16065},{"VersionControl":4},{"Undo":736},{"AssetDatabase":6101331},{"RestService":1518},{"EditorGi":376},{"License":3616},{"UnityConnect":25488},{"Collab":785},{"Upm":185824},{"DrivenProperties":80},{"LocalIPC":212},{"ProfilerEditor":10943},{"CoreBusinessMetrics":2876},{"AssetReference":32},{"IPCStream":32}]}
</code>
</details>

**How to reproduce**

- Create a new Unity project with version 2022.2.16
- Upload to a repo with the build CI config above

**Expected behavior**

It builds successfully

**Additional details**

This project was created on Unity version 2022.2.16 on M1 MacOS 12.6.2, and the CI and error logs are available [here](https://github.com/Beatzoid/tactics-rpg/actions/runs/4780907308/jobs/8498928459). Also, I originally had the error `Destruction is not allowed when there are still threads waiting on the semaphore` ([logs](https://github.com/Beatzoid/tactics-rpg/actions/runs/4780843488/jobs/8498824086)), but after updating to the version above this was the new error I got

**Comment by Beatzoid** [comment]
I fixed this issue, turns out it wasn't related to the "MemoryLeaks" JSON at all, it was because I didn't put any scenes in my build settings (File -> Build Settings on MacOS).

**Comment by webbertakken** [comment]
Thanks for reporting your solution.

Ref: https://github.com/game-ci/unity-actions/issues/166
