### ISSUE TITLE
Question: Dedicated server “workaround”

### ISSUE THREAD

**Issue by gotchipete** [game-ci/unity-actions#172]
Question… since Linux dedicated server is not supported yet, would a less than ideal workaround for our CI pipeline be to build a Linux version (with all assets included) and run that in our dedicated server environments (in headless mode)?

**Comment by davidmfinol** [comment]
That may be one option.
Though it is actually possible to make dedicated server builds. 
We're still working on improving documentation for it, but you may want to read about it: https://github.com/game-ci/documentation/issues/240

**Comment by davidmfinol** [comment]
Dedicated Server documentation has been merged, so closing this issue.
