### ISSUE TITLE
Can't activate license because page keeps refreshing

### ISSUE THREAD

**Issue by SethCram** [game-ci/unity-actions#176]
**Bug description**

I can't activate my unity license because the page at https://license.unity3d.com/manual linked to on the activation page of the docs https://game.ci/docs/github/activation/#converting-into-a-license keeps refreshing.

**How to reproduce**

Navigate to https://license.unity3d.com/manual and notice how it keep refreshing.

**Additional details**

I've tried stopping the page from refreshing and inputting my unity license but it errors out. 
![image](https://github.com/game-ci/unity-actions/assets/86444777/d7c378f3-5e1f-4603-8544-f133a7cb26ec)

Additionally, I tried using the license file held in C:\ProgramData\Unity, but I get the following message when trying to build a Unity project: 
```
Machine identification is invalid for current license.
Current license is invalid and cannot be activated. You must delete the license file and then activate a new license on current machine.
```

**Comment by SethCram** [comment]
Turns out this is a Firefox specific issue. I tried navigating to the link and uploading my license in Google Chrome and it worked.

**Comment by webbertakken** [comment]
Thank you for letting us know your solution!
