### ISSUE TITLE
Incomplete Complete Example (Testing a Package)

### ISSUE THREAD

**Issue by WAYN-Games** [game-ci/unity-actions#180]
**Bug description**

The [Complete Example (Testing a Package)](https://game.ci/docs/github/test-runner#complete-example-testing-a-package) is missing the additionally require configuration for testing packages instead of project described [here](https://game.ci/docs/github/test-runner#setting-packagemode)

**How to reproduce**

1; copy paste the sample in your package repository
2; struggle a few hours going through various ticket including but not limited to : Build failure from license [#82](https://github.com/game-ci/unity-actions/issues/82), Incorrect project path [#61](https://github.com/game-ci/unity-actions/issues/61) 
3; look at how action are implemented to end up [here](https://github.com/game-ci/unity-test-runner/blob/275df9854c669438c91b442cc3beb8bac3cbfc8c/dist/steps/run_tests.sh#L43) with a revelation !

-

**Expected behavior**

I quite enjoyed the opportunity to learn more about GitHub Action but if other don't want to have the same struggle, can you fix the sample ?

**Additional details**

![image](https://github.com/game-ci/unity-actions/assets/47318939/47a0f9bc-8d74-41cf-bf52-c023f8289986)

**Comment by webbertakken** [comment]
There's an edit button at the bottom of the docs page.

Happy to take contributions!

**Comment by WAYN-Games** [comment]
Done : https://github.com/game-ci/documentation/pull/429
Thanks !
