### ISSUE TITLE
androidAppBundle not being recognised as valid in game-ci/unity-builder@v3

### ISSUE THREAD

**Issue by geeklingo** [game-ci/unity-actions#182]
**Bug description**

Running game-ci/unity-builder@v3 to build an Android target fails to export the .aab file. The project continues to build as .apk despite the androidAppBundle flag being set.

The logs show this following error:
```
Unexpected input(s) 'androidAppBundle', valid inputs are ['targetPlatform', 'unityVersion', 'customImage', 'projectPath', 'buildName', 'buildsPath', 'buildMethod', 'customParameters', 'versioning', 'version', 'androidVersionCode', 'androidExportType', 'androidKeystoreName', 'androidKeystoreBase64', 'androidKeystorePass', 'androidKeyaliasName', 'androidKeyaliasPass', 'androidTargetSdkVersion', 'androidSymbolType', 'sshAgent', 'sshPublicKeysDirectoryPath', 'gitPrivateToken', 'githubOwner', 'chownFilesTo', 'allowDirtyBuild', 'postBuildSteps', 'preBuildSteps', 'containerHookFiles', 'customHookFiles', 'customCommandHooks', 'customJob', 'awsStackName', 'providerStrategy', 'cloudRunnerCpu', 'cloudRunnerMemory', 'readInputFromOverrideList', 'readInputOverrideCommand', 'kubeConfig', 'kubeVolume', 'kubeStorageClass', 'kubeVolumeSize', 'cacheKey', 'watchToEnd', 'cacheUnityInstallationOnMac', 'unityHubVersionOnMac', 'unityLicensingServer', 'dockerWorkspacePath']
```

**How to reproduce**

- use game-ci/unity-builder@v3
- include the flag: androidAppBundle: true

**Expected behavior**

Android package built as Android App Bundle (.aab)

**Additional details**

Worked fine in v2

**Comment by davidmfinol** [comment]
v3 has replaced `androidAppBundle` with `androidExportType`: https://game.ci/docs/github/builder#androidexporttype

**Comment by geeklingo** [comment]
Cool, i'll give that a go. FYI the example on https://game.ci/docs/github/deployment/android/ needs updating as that was my reference
