### ISSUE TITLE
Not all documented parameters are included in the action.yml

### ISSUE THREAD

**Issue by LucidDan** [game-ci/unity-actions#71]
Only a subset of the inputs documented are actually allowed in the action.yml, resulting in the following warning when I use customParameters, versioning, and other parameters:

```
##[warning]Unexpected input 'customParameters', valid inputs are ['unityVersion', 'targetPlatform', 'projectPath', 'buildName', 'buildsPath', 'buildMethod']
```

**Comment by davidmfinol** [comment]
Closing this issue, as I confirmed that all unity actions have proper input and documentation.
We can open a new issue if any specific ones were missed.
