### ISSUE TITLE
Building projects with video files not work?

### ISSUE THREAD

**Issue by Newbilius** [game-ci/unity-actions#73]
I include MP4 files to my game, and on windows build work perfectly, but with actions I get in log errors like this:

```
VideoClip import error for Assets/Resources/Video/03_get_chainsaw.mp4 
(Filename: ./Modules/AssetPipelineEditor/Public/VideoClipImporter.cpp Line: 390)
```
On the finish of action build created, but resources file not contain any video files.
After this I trying use option "transcode" on video files with converting to VP8, but it does not helped either.

**To Reproduce**
Build [this project](https://github.com/Newbilius/UnityFMVProofOfConcept/tree/unity_github_actions) by [unity-actions](https://github.com/Newbilius/UnityFMVProofOfConcept/actions) in branch "unity_github_actions"

**Expected behavior**
Success build with video files, included in resource file.

**Comment by webbertakken** [comment]
Did you ever find a solution to this @Newbilius ?

**Comment by Newbilius** [comment]
> Did you ever find a solution to this @Newbilius ?

No, I didn’t find it :-(

**Comment by chrishultin** [comment]
@Newbilius @webbertakken There's a very limited subset of video codec support in Unity on Linux - take a look here for more info.  https://docs.unity3d.com/Manual/VideoSources-FileCompatibility.html
