### ISSUE TITLE
Make a tutorial about setting a project with CI

### ISSUE THREAD

**Issue by Ozker24** [game-ci/unity-actions#94]
**Context**

I've been several hour trying these out and I can make it right, I'm following the documentation and a video about this but It doesn't work

**Suggested solution**

I suggest to make a video tutorial step by step on setting the git, the unity project and the actions

**Considered alternatives**

**Additional details**

**Comment by webbertakken** [comment]
Excellent idea. We should definitely do as time permits!

**Comment by frostebite** [comment]
@Ozker24 which step are you getting stuck on?

It's very useful to hear your perspective coming at it with fresh eyes!

**Comment by Ozker24** [comment]
Hi, I actually managed to set the Continuous integration but it was really
hard to set it, as the documentation wasn't updated. Where I was stuck was
in setting the git hub actions for continuous integration and unit testing.

Any help I can give tell me I'm glad to help!

**Comment by davidmfinol** [comment]
There is now a video tutorial here: https://game.ci/docs/github/getting-started#video-tutorial
