### ISSUE TITLE
Readme link points to the old docker list

### ISSUE THREAD

**Issue by erdostamasa** [game-ci/unity-actions#95]
The "list" link points to the deprecated docker repo.
![image](https://user-images.githubusercontent.com/62765033/107864560-bbff0b80-6e5d-11eb-93e8-51cb82ea16f6.png)

It points to: https://hub.docker.com/r/gableroux/unity3d/tags
It should point to: https://hub.docker.com/r/unityci/editor/tags?page=1&ordering=last_updated

**Comment by webbertakken** [comment]
Will be fixed in v2 of the docs after https://github.com/game-ci/documentation/pull/88 is merged.
