### ISSUE TITLE
Error while uploading artifact to license server

### ISSUE THREAD

**Issue by jcs090218** [game-ci/unity-actions#98]
I am getting the error

```
serial has reached the maximum number of activations.
```

when I tried to activate the license with the artifact `.alf` file... What did I do wrong? 😕

**Comment by GabLeRoux** [comment]
There is this related unity forum you:  
https://forum.unity.com/threads/unity-pro-serial-has-reached-the-maximum-number-of-activations-disable-existing-activations-to-re.441268/

Have a look at the number of seats being used in your Unity account for this serial. There is usually a limited number of activations for unity pro and one must return the license after runs.

See related documentation:  
https://game.ci/docs/github/returning-a-license#returning-a-license
